import { CellTypes } from "../enums";

export const MAZE1_REQUIRED_STEPS = 48;
export const MAZE1_WIDTH = 18;
export const MAZE1_HEIGHT = 16;
export const MAZE1_DATA = new Map([
    [[1, 1], CellTypes.END],
    [[1, 3], CellTypes.CLOSED],
    [[2, 3], CellTypes.CLOSED],
    [[3, 3], CellTypes.CLOSED],
    [[3, 12], CellTypes.CLOSED],
    [[4, 3], CellTypes.CLOSED],
    [[4, 6], CellTypes.CLOSED],
    [[4, 7], CellTypes.CLOSED],
    [[4, 8], CellTypes.CLOSED],
    [[4, 9], CellTypes.CLOSED],
    [[4, 10], CellTypes.CLOSED],
    [[4, 11], CellTypes.CLOSED],
    [[4, 12], CellTypes.CLOSED],
    [[5, 3], CellTypes.CLOSED],
    [[5, 12], CellTypes.CLOSED],
    [[6, 3], CellTypes.CLOSED],
    [[6, 12], CellTypes.CLOSED],
    [[6, 14], CellTypes.CLOSED],
    [[6, 15], CellTypes.CLOSED],
    [[6, 16], CellTypes.CLOSED],
    [[7, 3], CellTypes.CLOSED],
    [[7, 4], CellTypes.CLOSED],
    [[7, 5], CellTypes.CLOSED],
    [[7, 6], CellTypes.CLOSED],
    [[7, 7], CellTypes.CLOSED],
    [[7, 8], CellTypes.CLOSED],
    [[7, 9], CellTypes.CLOSED],
    [[7, 12], CellTypes.CLOSED],
    [[8, 12], CellTypes.CLOSED],
    [[9, 12], CellTypes.CLOSED],
    [[10, 5], CellTypes.CLOSED],
    [[10, 6], CellTypes.CLOSED],
    [[10, 7], CellTypes.CLOSED],
    [[10, 8], CellTypes.CLOSED],
    [[10, 9], CellTypes.CLOSED],
    [[10, 10], CellTypes.CLOSED],
    [[10, 11], CellTypes.CLOSED],
    [[10, 12], CellTypes.CLOSED],
    [[11, 5], CellTypes.CLOSED],
    [[12, 5], CellTypes.CLOSED],
    [[13, 5], CellTypes.CLOSED],
    [[13, 9], CellTypes.START],
    [[14, 5], CellTypes.CLOSED]
]);